version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to hub.docker.com
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build docker image
          command: docker build -t jayamorin/packer-builder:latest .
      - run:
          name: Tag docker build
          command: |
            docker tag jayamorin/packer-builder:latest jayamorin/packer-builder:$CIRCLE_SHA1
      - run:
          name: Push docker build to hub.docker.com
          command: |
            docker push jayamorin/packer-builder:$CIRCLE_SHA1
            docker push jayamorin/packer-builder:latest

workflows:
  version: 2
  packer-builder:
    jobs:
      - build:
          filters:
            branches:
              only: master